### ISSUE TITLE
failed to resolve lj_bcwrite

### ISSUE THREAD

**Issue by Heyter** [everyday-as/gluac#2]
failed to resolve lj_bcwrite
error loading lua_shared

i think pattern is dead "\x83\xEC\x24\x8B\x4C\x24\x2C\x8B\x54\x24\x30\x8B\x44\x24\x28\x89"

**Comment by Heyter** [comment]
resolved.

**Comment by Marcuzz** [comment]
I'm not sure if you ever figured it out (or even care still as this issue was opened a long time ago), but the symbol now is:

```
\x83\xEC\x24\x8B\x44\x24\x2C\x8B\x4C\x24\x28\x89\x44\x24\x10\x8B
```

**Comment by Heyter** [comment]
> I'm not sure if you ever figured it out (or even care still as this issue was opened a long time ago), but the symbol now is:
> 
> ```
> \x83\xEC\x24\x8B\x44\x24\x2C\x8B\x4C\x24\x28\x89\x44\x24\x10\x8B
> ```

error C2390 visual studio 2019 windows.
incorrect storage class 'auto'

`LJ_STATIC_ASSERT(offsetof(GChead, gclist) == offsetof(GCtab, gclist));`

**Comment by Marcuzz** [comment]
Hmm, I didn't have this error yesterday when I wasn't using VS 2019 (I was simply compiling it with msbuild manually using god knows what version) - but now that I've installed VS 2019 I am experiencing this error as well.

**Comment by Heyter** [comment]
> Hmm, I didn't have this error yesterday when I wasn't using VS 2019 (I was simply compiling it with msbuild manually using god knows what version) - but now that I've installed VS 2019 I am experiencing this error as well.

try it

```
#undef__cplusplus

or

#define offsetof(s,m) ((size_t)&(((s*)0)->m))
```

**Comment by Marcuzz** [comment]
Yeah, that works
